openrr/urdf-viz

- Cargo.toml
- src/lib.rs
Helps resolve https://github.com/OTL/gear/issues/5
> Update many versions

- src/urdf_viewer.rs
This PR add a key binding that resets all joint positions to zero.
Currently "z" is the key to reset joints but I welcome any alternative key for that.
> Add a key binding to reset joint positions

- Cargo.toml
- src/bin/urdf-viz.rs
- src/viewer.rs
> Use k=0.21.0

- README.md
Refs: https://www.rust-lang.org/tools/install
> Update rustup install command in docs

- Cargo.toml
There is no API change, but I'd like to release compiled binary.
> Release v0.23.1

- Cargo.toml
- README.md
Changes:
- Update (public) dependencies (#48)
> Release v0.24.0

- README.md
We need cmake if we want to use assimp.
> [README] Add description about cmake

- src/bin/urdf-viz.rs
Closes #43
https://user-images.githubusercontent.com/43724913/114505401-49e35100-9c6b-11eb-9242-0bab88270b9c.mov
> Reset robot pose by z key

- Cargo.toml
Changes: 
- Update (public) dependencies (#57)
- Reset robot pose by z key (#59)
> Release 0.26.0

- .github/workflows/ci.yml
- src/bin/urdf-viz.rs
- src/mesh.rs
- src/viewer.rs
- src/web_server.rs
- Fix clippy::field_reassign_with_default warning
- Fix clippy::explicit_counter_loop warning
- Fix clippy::expect_fun_call warning
- Ignore clippy::too_many_arguments warning
- Ignore clippy::type_complexity warning
- Add clippy check to CI
> Fix clippy warnings

- src/app.rs
- src/lib.rs
> Re-export kiss3d

- src/viewer.rs
Fixes #73 
refs: https://github.com/openrr/urdf-viz/commit/7c8a77b45ff35442ad5f2a6b2fbcad60d1dc72d1
> Adjust dist_step

- Cargo.toml
Changes:
- Fix bug in zoom-in functionality (#74)
Closes #76
> Release 0.27.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
This relaxes the requirement for glibc on prebuilt binary for x86_64-unknown-linux-gnu.
> Use ubuntu-18.04 instead of ubuntu-latest

- Cargo.toml
- examples/wasm/src/lib.rs
- src/mesh.rs
- src/urdf.rs
- src/utils.rs
- src/viewer.rs
(e0636a0fca2cdf0dedace87b814f325cce71bc38, 4773a3678224736e2807fea941e781a071b392b1)
```
cd examples/wasm && npm run serve
```
Open 
- http://localhost:8080/?urdf=https://raw.githubusercontent.com/openrr/urdf-viz/e0636a0fca2cdf0dedace87b814f325cce71bc38/sample.urdf  
- http://localhost:8080/?urdf=https://raw.githubusercontent.com/openrr/urdf-viz/4773a3678224736e2807fea941e781a071b392b1/sample.urdf 
in a browser.
> Support obj on wasm

- Cargo.toml
- README.md
- src/mesh.rs
- src/utils.rs
> Support stl without assimp

- .github/workflows/release.yml
- src/app.rs
- src/assimp_utils.rs
- src/bin/urdf-viz.rs
- src/lib.rs
- src/utils.rs
- src/viewer.rs
> Apply rust_2018_idioms and missing_debug_implementations lints

- Cargo.toml
Changes:
- Avoid potential license issues #88
- Add Opt::create_ik_constraints #87
- Expose more utilities #86
> Release 0.28.1

- src/app.rs
Currently, when you press ctrl-r on the web version, browser's tab reload (ctrl-r key) is applied after urdf-viz's randomization (r key) is applied.
> Avoid conflicts with browser keyboard shortcuts

- Cargo.toml
> Release 0.30.0

- src/app.rs
- src/handle.rs
- src/lib.rs
- src/point_cloud.rs
It is not available from UI or web API, for now.
> Add point cloud to library API

- Cargo.toml
- src/app.rs
- src/utils.rs
Use reloading of tab (ctrl-r) instead.
This may improve performance somewhat.
> Remove reload from wasm

- src/app.rs
- src/handle.rs
- src/utils.rs
This also reverts #102 because it was found that it was not sufficient for our use case.
> Add RobotStateHandle::set_robot

- Cargo.toml
Depend on ~~https://github.com/openrr/k/pull/71~~ https://github.com/openrr/k/pull/72
- k 0.25 -> 0.26
- kiss3d 0.31 -> 0.32
> Update kiss3d and k

- .clippy.toml
- .github/workflows/ci.yml
- Cargo.toml
- src/app.rs
- src/handle.rs
- src/utils.rs
Same as https://github.com/openrr/openrr/pull/525 and https://github.com/openrr/k/pull/68.
> Use parking_lot::Mutex

- Cargo.toml
- LICENSE
Changes:
- #117 
- #115 
- #114
> Release 0.33.0

- Cargo.toml
> Release 0.33.1

- src/mesh.rs
Prevents #123 from becoming a breaking change.
> Make mesh::read_stl private

- Cargo.toml
Changes:
- #124 
- #121 
- #122
> Release 0.34.0

- Cargo.toml
- src/web_server.rs
This patch will remove a lot of duplicate dependencies in openrr.
> Switch to warp

- Cargo.toml
> Release 0.35.0

- src/app.rs
Press 'f' to show the RGB frames, which includes fixed frames.
> Support show frames

- Cargo.toml
- src/app.rs
- src/handle.rs
> Allow RobotStateHandle to handle multiple objects at the same time

- src/app.rs
- src/handle.rs
> Add lib API to set object relationship

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/139
- https://github.com/openrr/urdf-viz/pull/136
- https://github.com/openrr/urdf-viz/pull/135
- https://github.com/openrr/urdf-viz/pull/134
- https://github.com/openrr/urdf-viz/pull/133
- https://github.com/openrr/urdf-viz/pull/132
- https://github.com/openrr/urdf-viz/pull/130
- https://github.com/openrr/urdf-viz/pull/129
> Release 0.36.0

- Cargo.toml
- README.md
- src/mesh.rs
- src/utils.rs
https://github.com/openrr/mesh-loader/pull/1
https://github.com/openrr/mesh-loader/pull/2
> Switch to mesh-loader

- Cargo.toml
- src/bin/urdf-viz.rs
- src/web_server.rs
The first commit is needed for https://github.com/openrr/openrr/pull/605.
Changes:
- https://github.com/openrr/urdf-viz/pull/145
> Release 0.37.0

- Cargo.toml
> Release 0.37.1

- Cargo.toml
- src/errors.rs
- src/mesh.rs
- src/urdf.rs
On wasm, this is already supported.
Depend on https://github.com/openrr/urdf-rs/pull/43.
> Support http:// and https:// meshes on native

- Cargo.toml
Changes:
- #156
- #155
- #154
- #152
- #151
Updating kiss3d is a  breaking change:
https://github.com/openrr/urdf-viz/blob/8c04d178af744fe2b713ebca35e2a3f1bc2f4948/Cargo.toml#L20
> Release 0.38.0

- Cargo.toml
- examples/wasm/Cargo.toml
- examples/wasm/src/lib.rs
- src/app.rs
- src/errors.rs
- src/lib.rs
- src/mesh.rs
- src/urdf.rs
- src/utils.rs
This allows it to work on both wasm32 and wasm64.
> Replace `target_arch = "wasm32"` with `target_family = "wasm"`

- .github/workflows/ci.yml
Currently, it is built with debug mode with no optimization (opt-level=0).
> Optimize wasm to be uploaded to gh-pages

- src/viewer.rs
Adapt the following change https://github.com/sebcrozet/kiss3d/pull/283, without it zooming is broken
> Fix scroll zoom dist_step

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/162
- https://github.com/openrr/urdf-viz/pull/160
> Release 0.38.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
refs: https://github.com/actions/runner-images/issues/6002
> Remove uses of GitHub provided ubuntu-18.04 runner

- sample.urdf
- src/urdf.rs
> Implement capsule

- Cargo.toml
> Release 0.38.2

- Cargo.toml
- examples/wasm/Cargo.toml
- examples/wasm/src/lib.rs
This removes the need for log feature of tracing crate.
> Use tracing-wasm in wasm example

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/172
> Release 0.39.0

- README.md
> Fix installation command of no-default-features

- src/app.rs
- src/utils.rs
And tweaks the behavior on the edge case (reject some invalid cases).
> Add test for replace_package_with_path and create_package_path_map

- Cargo.toml
> Release 0.40.0

- Cargo.toml
> Release 0.41.0

- Cargo.toml
- src/web_server.rs
https://github.com/tokio-rs/axum/releases/tag/axum-v0.6.0
This also removes hyper from public dependencies.
> Update axum to 0.6

- .deny.toml
- .github/.cspell/project-dictionary.txt
- .github/workflows/ci.yml
Checks licenses and advisories.
https://github.com/EmbarkStudios/cargo-deny
> Run cargo-deny in CI

- src/app.rs
- src/bin/urdf-viz.rs
- src/viewer.rs
This PR is to add requested features in #192.
**Menu option**
- Assigned for show menu in screen or not to `m` key.
- If set command line option `-m`, menu is not show in default. (It appear if you use `m` key).
**Axis scale option**
- You can set axis scale using command line option `-s`.
For eaxmple, if you run like following, 
```bash
urdf-viz sample.urdf -s 0.5
```
all coordinate axes in the application will be reduced by half.
> Add feature to toggle menu and change axes scale.

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/197
- https://github.com/openrr/urdf-viz/pull/184
- https://github.com/openrr/urdf-viz/pull/188
- https://github.com/openrr/urdf-viz/pull/194
- https://github.com/openrr/urdf-viz/pull/199
- https://github.com/openrr/urdf-viz/pull/202
- https://github.com/openrr/urdf-viz/pull/200
> Release v0.42.0

- .github/dependabot.yml
- Cargo.toml
- examples/wasm/Cargo.toml
- src/urdf.rs
~~Depend on https://github.com/openrr/k/pull/116~~
> Update k and urdf-rs

- Cargo.toml
> Release 0.43.0

- Cargo.toml
> Release 0.43.1

- src/assimp_utils.rs
> Fix type conversion in `aiGetMaterialColor` argument

- src/app.rs
- src/bin/urdf-viz.rs
- src/mesh.rs
- src/urdf.rs
- src/viewer.rs
> Add `disable-assimp` CLI flag

- .github/workflows/ci.yml
- Cargo.toml
- examples/wasm/README.md
- examples/wasm/src/lib.rs
- src/app.rs
> Fix wasm example

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/226
- https://github.com/openrr/urdf-viz/pull/222
- https://github.com/openrr/urdf-viz/pull/219
- https://github.com/openrr/urdf-viz/pull/216
> Release 0.44.0

- .clippy.toml
- .github/.cspell/project-dictionary.txt
- Cargo.toml
- src/app.rs
- src/handle.rs
- src/utils.rs
See https://github.com/openrr/openrr/pull/885 for more.
> Use std::sync::Mutex instead of parking_lot

- Cargo.toml
- examples/wasm/Cargo.toml
- src/assimp_utils.rs
- src/bin/urdf-viz.rs
- src/lib.rs
- src/point_cloud.rs
The first and second commits are the same as https://github.com/openrr/openrr/pull/886.
The last one is a simplification that I realized was possible while writing the second commit.
> Use [lints] in Cargo.toml and apply more lints

- .github/.cspell/project-dictionary.txt
- Cargo.toml
- src/mesh.rs
- src/utils.rs
Use a new easy-to-use API added in https://github.com/openrr/mesh-loader/pull/31.
> Use new loader API of mesh-loader

- examples/wasm/Cargo.toml
Same as https://github.com/openrr/openrr/pull/899.
> Use version-less manifests for example

- src/assimp_utils.rs
Workaround for assimp-rs the following panic (e.g., happens when loading collada mesh used in hsr_description/robots/hsrb4s.urdf)
```
thread 'main' panicked at /Users/taiki/.cargo/registry/src/index.crates.io-6f17d22bba15001f/assimp-sys-0.3.1/src/types/string.rs:26:34:
range end index 8746397738037411848 out of range for slice of length 1024
```
> Work around assimp-rs bug that causes panic

- src/app.rs
- src/assimp_utils.rs
This will be stabilized in Rust 1.77, which is scheduled to be released this evening.
> Use C string literal

- .github/.cspell/project-dictionary.txt
- .github/workflows/ci.yml
- .github/workflows/release.yml
Follow-up to https://github.com/openrr/homebrew-tap/pull/41 / https://github.com/openrr/urdf-viz/issues/233.
> Distribute prebuilt binary for aarch64 macOS

- .github/.cspell/rust-dependencies.txt
https://github.com/openrr/urdf-viz/actions/runs/9148593529/job/25151305082
> Fix CI failure

- src/app.rs
> Move the menu to the right side of the window

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/251
- https://github.com/openrr/urdf-viz/pull/252
> Release 0.45.2

- Cargo.toml
> Release 0.46.0

- Cargo.toml
Changes:
- https://github.com/openrr/urdf-viz/pull/274
- https://github.com/openrr/urdf-viz/pull/270
- https://github.com/openrr/urdf-viz/pull/266
> Release 0.46.1 & Document how to publish

- .deny.toml
- .github/workflows/ci.yml
- examples/wasm/package.json
- examples/wasm/webpack.config.js
> Fix CI failures
